### ISSUE TITLE
Battle

### ISSUE THREAD

**Issue by lindskogen** [jolin1337/Pokemans#2]
Man ska kunna slåss mot varandra, den andra personen ska ta skada... Om den ena personens health går ner till en viss nivå kan man krama den... Ungefär som att försöka fånga Pokémon i det riktiga spelet! _Vilken otroligt bra idé!_

**Comment by lindskogen** [comment]
Varför stängde du den..?

**Comment by jolin1337** [comment]
jag visste inte vad knappen gjorde så jag klickade

**Comment by lindskogen** [comment]
Makes sense....

**Comment by jolin1337** [comment]
så varför assignade du den till mig?

**Comment by lindskogen** [comment]
Kan inte ändra den!!! :O
