### ISSUE TITLE
Intro/Story

### ISSUE THREAD

**Issue by jolin1337** [jolin1337/Pokemans#6]
En textbaserad introduktion om spelet 
programmera ett intro med text som finns på gdocs

**Comment by lindskogen** [comment]
Bara själva texten menar du då? Eller kod för att visa texten?

**Comment by jolin1337** [comment]
Alltså text ut mot spelaren, ett introduktion till spelet.

**Comment by lindskogen** [comment]
Alltså texten...

**Comment by jolin1337** [comment]
Texten finns redan på gdocs typ

**Comment by lindskogen** [comment]
Okej, så vad ska fixas?

**Comment by jolin1337** [comment]
intro i spelet!

**Comment by lindskogen** [comment]
Och det innebär?
